### ISSUE TITLE
Just a question, how to set  six-digt models in Beast?

### ISSUE THREAD

**Issue by actledge** [BEAST2-Dev/bModelTest#5]
I got the best six-digit models using bModeltest, but I don't know how to set them in Beast2, other than the ones in the Beast like HKY, how to set other models like 123321(K81)?
 I understand from the official documentation that it only requires a few additional Settings on the base of HKY, It is also mentioned in the documentation that the difference here is the substitution rate of CT and RT, It also mentioned that "Arrows indicate that the model at the tail is nested inside the model at the head and can be obtained by adding one parameter to the model."

but I don't know exactly what additional parameter Settings this corresponds to.
 I found on the Internet that there were other people who had similar problems.
and someone told him ： the K81 = HKY + equal base freq , 
but，how do I derive "equal base freq" from "substitution rate of CT and RT".

This may be a superficial question, but I thought it would be more user-friendly for beginners like me to provide relevant documentation or some other clues.
Can you provide relevant information or literature in the help document?

**Comment by rbouckaert** [comment]
In general, there is no need to fix the model, unless you have specific reasons (e.g. test for specific relations between some of the rates). The bModelTest site model will perform Bayesian model averaging over the available site models, and usually, these site models are not of any interest to the research question that you are interested in. So, most of the time you just select the bModelTest site model and (apart from checking all parameters converge) forget about it.

If you still need to fix the model, select the GTR model, and click menu "Mode/Allow parameter linking" and next to the parameters in the GTR model a chain icon appears. When clicking the chain icon you can select the parameter to link with. For instance, for model 123321, you link AC with GT, then link AG with CT and finally AT with CG. It is a bit fragile, so make sure not to make mistakes that need to be undone.

Hope I understood the question.

**Comment by rbouckaert** [comment]
Also, see here for setting up more of the model: https://github.com/BEAST2-Dev/bModelTest/wiki/How-to-use-bModelTest#setting-up-a-non-standard-substitution-model-in-beauti

**Comment by actledge** [comment]
oh... so actually, I just need to select bModelTest in BEAUti ,and run beast only once. Instead of running the Beast once to determine the optimal substitution model and then using the optimal model to run the Beast a second time?
Do I understand this correctly?  If so, then I have no further questions. 
That's very helpful.
Thank you very much for your reply!

**Comment by rbouckaert** [comment]
Yes, just run BEAST once with bModelTest, unless you are interested in the particular properties of the individual components of the site model and how they influence the result of the analysis (which is unusual).
